### ISSUE TITLE
Gif visualization

### ISSUE THREAD

**Issue by SnowdenLee** [kvablack/ddpo-pytorch#1]
Hi, 
thanks for the reimplementation! Your Gif visualization using [iceberg](https://github.com/revalo/iceberg) is super nice! Could you maybe also share the code of it? 
Thanks a lot!

**Comment by kvablack** [comment]
Sure thing, here it is: https://gist.github.com/kvablack/3e2d3cf849107f76b13d1e3cd31c0bf6

It takes as input MP4 videos, which I created by just loading each LoRA checkpoint in sequence and generating an image with the same seed across checkpoints.
