### ISSUE TITLE
OOM despite using A100-80GB GPU and 128GB CPU memory (+16 CPUs per task)

### ISSUE THREAD

**Issue by noshaba** [kvablack/ddpo-pytorch#4]
Hi,

I am experiencing out-of-memory issues with this codebase even at the start of epoch 0.0, despite using an A100 with 80GB VRAM and 128GB RAM :/

I am using the following changes in the config file:
config.sample.batch_size = 1
config.sample.num_batches_per_epoch = 256
config.train.batch_size = 1
config.train.gradient_accumulation_steps = 128

**Comment by kvablack** [comment]
That should be plenty of memory, even without LoRA. Can you paste the full error?

**Comment by noshaba** [comment]
Hi! Figured it out... Was an issue with my base container and CUDA 😅
