### ISSUE TITLE
On reproducing LLaVA alignment experiments. 

### ISSUE THREAD

**Issue by bhattg** [kvablack/ddpo-pytorch#5]
Hi! I've a couple of questions on the LLaVa alignment:
- Which LLaVA model was used for the experiment? Was it the 7B one or 13B one? 
- What precision was used w/ LoRA based results? Was that bf16 of full fp32?

**Comment by kvablack** [comment]
I used the 13B variant of LLaVA, and all experiments were run with fp16 precision.

**Comment by bhattg** [comment]
Thanks, closing the issue now. :-)
